root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/..."
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules"]
  exclude_file = ["output.css"]
  exclude_regex = ["_test.go", "_templ.go"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = "DB_USER=postgres DB_HOST=127.0.0.1 DB_PASSWORD=password DB_NAME=hypermediashop DB_PORT=5432 ./tmp/main"
  include_dir = []
  include_ext = ["go", "templ"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = ["npx tailwindcss -i ./static/css/input.css -o ./static/css/output.css", "templ generate -path ./templates"]
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
